package media

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
)

const (
	cookiesEnvBrowser = "MR_COOKIES_BROWSER"
	cookiesEnvURL     = "MR_COOKIES_URL"
	cookiesEnvMaxAge  = "MR_COOKIES_MAX_AGE_HOURS"
)

var supportedBrowsers = []string{"chrome", "chromium", "firefox", "edge", "brave", "opera", "vivaldi", "safari"}

// ExtractDomainFromURL extracts a clean .domain.com string from a URL
func ExtractDomainFromURL(targetURL string) string {
	if targetURL == "" {
		return ".youtube.com"
	}
	u, err := url.Parse(targetURL)
	if err != nil || u.Host == "" {
		if u2, err2 := url.Parse("https://" + targetURL); err2 == nil && u2.Host != "" {
			u = u2
		} else {
			return ".youtube.com"
		}
	}
	host := u.Hostname()
	host = strings.TrimPrefix(host, "www.")
	if !strings.HasPrefix(host, ".") {
		host = "." + host
	}
	return host
}

// NormalizeCookiesToNetscape converts any cookie format (Netscape, JSON array/object, Raw header string)
// into valid Netscape HTTP Cookie File format compatible with yt-dlp.
func NormalizeCookiesToNetscape(raw string, targetURL string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}

	// 1. Check if already in Netscape format
	if strings.Contains(raw, "\t") || strings.HasPrefix(raw, "# Netscape") || strings.HasPrefix(raw, "# HTTP Cookie File") {
		var sb strings.Builder
		if !strings.HasPrefix(raw, "# Netscape") {
			sb.WriteString("# Netscape HTTP Cookie File\n# Generated by KV Download\n\n")
		}
		sb.WriteString(raw)
		sb.WriteString("\n")
		return sb.String()
	}

	defaultDomain := ExtractDomainFromURL(targetURL)
	expiry := time.Now().Add(365 * 24 * time.Hour).Unix()

	// 2. Check if JSON Array (e.g. from Cookie-Editor / EditThisCookie)
	if strings.HasPrefix(raw, "[") && strings.HasSuffix(raw, "]") {
		var items []map[string]interface{}
		if err := json.Unmarshal([]byte(raw), &items); err == nil && len(items) > 0 {
			var sb strings.Builder
			sb.WriteString("# Netscape HTTP Cookie File\n# Converted from JSON by KV Download\n\n")
			for _, it := range items {
				name, _ := it["name"].(string)
				value, _ := it["value"].(string)
				if name == "" {
					continue
				}
				domain, _ := it["domain"].(string)
				if domain == "" {
					domain = defaultDomain
				}
				if !strings.HasPrefix(domain, ".") && !strings.Contains(domain, "localhost") {
					domain = "." + domain
				}
				path, _ := it["path"].(string)
				if path == "" {
					path = "/"
				}
				secure := "FALSE"
				if sec, ok := it["secure"].(bool); ok && sec {
					secure = "TRUE"
				}
				expVal := expiry
				if exp, ok := it["expirationDate"].(float64); ok && exp > 0 {
					expVal = int64(exp)
				}
				includeSubdomain := "TRUE"
				if !strings.HasPrefix(domain, ".") {
					includeSubdomain = "FALSE"
				}

				sb.WriteString(fmt.Sprintf("%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
					domain, includeSubdomain, path, secure, expVal, name, value))
			}
			return sb.String()
		}
	} else if strings.HasPrefix(raw, "{") && strings.HasSuffix(raw, "}") {
		// Key-Value JSON object
		var kvMap map[string]interface{}
		if err := json.Unmarshal([]byte(raw), &kvMap); err == nil && len(kvMap) > 0 {
			var sb strings.Builder
			sb.WriteString("# Netscape HTTP Cookie File\n# Converted from Key-Value JSON by KV Download\n\n")
			for k, v := range kvMap {
				valStr := fmt.Sprintf("%v", v)
				if k != "" && valStr != "" {
					sb.WriteString(fmt.Sprintf("%s\tTRUE\t/\tFALSE\t%d\t%s\t%s\n",
						defaultDomain, expiry, k, valStr))
				}
			}
			return sb.String()
		}
	}

	// 3. Raw header format: "key1=val1; key2=val2" or "Cookie: key1=val1"
	clean := strings.TrimPrefix(raw, "Cookie:")
	clean = strings.TrimPrefix(clean, "cookie:")
	clean = strings.TrimSpace(clean)

	var sb strings.Builder
	sb.WriteString("# Netscape HTTP Cookie File\n# Converted from Cookie Header by KV Download\n\n")
	hasValidCookies := false

	tokens := strings.FieldsFunc(clean, func(r rune) bool {
		return r == ';' || r == '\n' || r == '\r'
	})

	for _, token := range tokens {
		token = strings.TrimSpace(token)
		if token == "" || strings.HasPrefix(token, "#") {
			continue
		}
		parts := strings.SplitN(token, "=", 2)
		if len(parts) == 2 {
			k := strings.TrimSpace(parts[0])
			v := strings.TrimSpace(parts[1])
			if k != "" {
				sb.WriteString(fmt.Sprintf("%s\tTRUE\t/\tFALSE\t%d\t%s\t%s\n",
					defaultDomain, expiry, k, v))
				hasValidCookies = true
			}
		}
	}

	if hasValidCookies {
		return sb.String()
	}

	return raw
}

// CreateEphemeralCookieFile creates a temporary cookie file for the specific task/scan
// and returns the filepath and a cleanup function. Never persists cookies permanently.
func CreateEphemeralCookieFile(cookiesContent string, targetURL string) (string, func(), error) {
	if strings.TrimSpace(cookiesContent) == "" {
		return "", func() {}, nil
	}

	netscapeData := NormalizeCookiesToNetscape(cookiesContent, targetURL)
	if strings.TrimSpace(netscapeData) == "" {
		return "", func() {}, nil
	}

	tmpFile := filepath.Join(os.TempDir(), "kv_cookie_"+uuid.New().String()+".txt")
	if err := os.WriteFile(tmpFile, []byte(netscapeData), 0600); err != nil {
		return "", func() {}, err
	}

	cleanup := func() {
		_ = os.Remove(tmpFile)
	}

	return tmpFile, cleanup, nil
}

// RefreshCookiesFromBrowser regenerates cookies.txt from the configured browser
// if the file is missing or stale. Returns true if a cookies.txt is available afterwards.
func RefreshCookiesFromBrowser() bool {
	cookiesPath := getCookiesPath()

	if cookiesFileFresh(cookiesPath) {
		return true
	}

	browser := strings.TrimSpace(os.Getenv(cookiesEnvBrowser))
	if browser == "" {
		log.Info().Msgf("cookies.txt is missing or stale and %s is not set — skipping auto-refresh", cookiesEnvBrowser)
		return false
	}

	if !isSupportedBrowser(browser) {
		log.Warn().Msgf("unsupported browser %q for %s — skipping auto-refresh", browser, cookiesEnvBrowser)
		return false
	}

	log.Info().Msgf("Refreshing cookies.txt from browser %q...", browser)
	if err := extractCookiesFromBrowser(browser, cookiesPath); err != nil {
		log.Warn().Err(err).Msg("cookie extraction failed")
		return false
	}
	log.Info().Msgf("cookies.txt refreshed from browser %q", browser)
	return true
}

func cookiesFileFresh(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}

	maxAge := 24 * 7 // hours, default 7 days
	if v := strings.TrimSpace(os.Getenv(cookiesEnvMaxAge)); v != "" {
		if n, convErr := strconv.Atoi(v); convErr == nil && n > 0 {
			maxAge = n
		}
	}

	if time.Since(info.ModTime()) < time.Duration(maxAge)*time.Hour {
		return true
	}
	log.Info().Msgf("cookies.txt is older than %d hours — refreshing", maxAge)
	return false
}

func extractCookiesFromBrowser(browser, cookiesPath string) error {
	url := strings.TrimSpace(os.Getenv(cookiesEnvURL))
	if url == "" {
		url = "https://www.tiktok.com/"
	}

	args := []string{
		"--cookies-from-browser", browser,
		"--cookies", cookiesPath,
		"--skip-download",
		url,
	}

	cmd := exec.Command("yt-dlp", args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		log.Debug().Msgf("yt-dlp cookie extraction output: %s", output)
	}

	if _, statErr := os.Stat(cookiesPath); statErr != nil {
		return statErr
	}
	return nil
}

func isSupportedBrowser(browser string) bool {
	for _, b := range supportedBrowsers {
		if b == browser {
			return true
		}
	}
	return false
}

// getWorkingCookiesPath copies cookiesPath to a writable temporary file in /tmp
// to prevent yt-dlp from crashing when save_cookies() tries to open read-only cookies files on exit.
func getWorkingCookiesPath(cookiesPath string) string {
	if !isReadableFile(cookiesPath) {
		return ""
	}

	tmpPath := filepath.Join(os.TempDir(), "mr_working_cookies.txt")
	data, err := os.ReadFile(cookiesPath)
	if err != nil {
		return cookiesPath
	}

	if err := os.WriteFile(tmpPath, data, 0644); err == nil {
		return tmpPath
	}

	return cookiesPath
}
